services:
  - type: web
    rootDir: server
    name: doo-app
    env: docker
    plan: free
    region: ohio
    envVars:
      - key: DOO_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
