version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.wsl
      additional_contexts:
        doo_release: \\wsl.localhost\Ubuntu\home\nayan\doo-builds\linux\release
        doo_std: x:\Projects\doo\std
    image: doo-url-shortner-server:wsl
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - DOO_REWRITE_SUPABASE_POOLER=0
      - DOO_DB_DISABLE_PREPARED_STATEMENTS=1
    ports:
      - "3001:3001"
    env_file:
      - .env
